---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: "Instala MySql"
      apt:
        name: ['mysql-server','python-mysqldb']
        state: latest
      become: yes    
    - name: 'Cria o banco do MySql'
      mysql_db:
        name: "{{wp_db_name}}"
        state: present
      become: yes
    - name: 'Cria usuário do banco wordpress_db no MySql'
      mysql_user:
        name: "{{wp_db_username}}"
        password: "{{wp_db_passwd}}"
        priv: "{{wp_db_name}}.*:ALL"
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{wp_host_ip}}"
      become: yes
      notify:
        - restart mysql

- hosts: wordpress

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala Apache e PHP5'
      apt:
        name: ['php7.2', 'php7.2-common','apache2','libapache2-mod-php7.2','php7.2-gd','php7.2-mysql']
        state: latest
      become: yes
    - name: 'Baixa arquivo de instalação do wordpress'
      get_url:
        url: 'https://br.wordpress.org/wordpress-5.1.13-pt_BR.tar.gz'
        dest: '/tmp/wordpress-5.1.13-pt_BR.tar.gz'
    - name: 'Descompacta arquivo do wordpress'
      unarchive:
        src: '/tmp/wordpress-5.1.13-pt_BR.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes
    - name: 'Copia arquivo de configuração do wordpress'
      copy:
        src: "{{wp_install_dir}}/wp-config-sample.php"
        dest: "{{wp_install_dir}}/wp-config.php"
        remote_src: yes
      become: yes
    - name: 'Configura banco no arquivo wp-config.php'
      replace:
        path: "{{wp_install_dir}}/wp-config.php"
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
      with_items:
        - { regex: 'localhost', value: "{{wp_mysql_ip}}"}
        - { regex: 'nome_do_banco_de_dados_aqui', value: "{{wp_db_name}}"}
        - { regex: 'nome_de_usuario_aqui', value: "{{wp_db_username}}"}
        - { regex: 'senha_aqui', value: "{{wp_db_passwd}}"}
      become: yes
    - name: 'Copia arquivo de configuração do Apache'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache2

