---
- name: 'Baixa arquivo de instalação do wordpress'
  get_url:
    url: 'https://br.wordpress.org/wordpress-5.1.13-pt_BR.tar.gz'
    dest: '/tmp/wordpress-5.1.13-pt_BR.tar.gz'
- name: 'Descompacta arquivo do wordpress'
  unarchive:
    src: '/tmp/wordpress-5.1.13-pt_BR.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copia arquivo de configuração do wordpress'
  copy:
    src: "{{wp_install_dir}}/wp-config-sample.php"
    dest: "{{wp_install_dir}}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura banco no arquivo wp-config.php'
  replace:
    path: "{{wp_install_dir}}/wp-config.php"
    regexp: '{{ item.regex }}'
    replace: '{{ item.value }}'
    backup: yes
  with_items:
    - { regex: 'localhost', value: "{{wp_mysql_ip}}"}
    - { regex: 'nome_do_banco_de_dados_aqui', value: "{{wp_db_name}}"}
    - { regex: 'nome_de_usuario_aqui', value: "{{wp_db_username}}"}
    - { regex: 'senha_aqui', value: "{{wp_db_passwd}}"}
  become: yes

- name: 'Configura Apache para servir Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache2
