---
    - name: "Instala MySql"
      apt:
        name: ['mysql-server','python-mysqldb']
        state: latest
      become: yes    
    - name: 'Cria o banco do MySql'
      mysql_db:
        name: "{{wp_db_name}}"
        state: present
      become: yes
    - name: 'Cria usuário do banco wordpress_db no MySql'
      mysql_user:
        name: "{{wp_db_username}}"
        password: "{{wp_db_passwd}}"
        priv: "{{wp_db_name}}.*:ALL"
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{wp_host_ip}}"
      become: yes
      notify:
        - restart mysql
